# Generated by Django 5.2.5 on 2026-07-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoftequipment',
            name='category',
            field=models.CharField(blank=True, choices=[('chrono', 'Хронограф'), ('charger', 'Зарядное устройство'), ('battery', 'Аккумулятор'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='airsoftequipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='airsoftequipment',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='airsoftequipment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='max_players',
            field=models.PositiveIntegerField(default=30, verbose_name='Максимум игроков'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость участия'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='registered_players',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарегистрировано игроков'),
        ),
        migrations.AddField(
            model_name='gun',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guns/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gun',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='gun',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='gunaccessory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='gunaccessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gunaccessory',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='gunaccessory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='gunmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gunmodule',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='gunmodule',
            name='material',
            field=models.CharField(blank=True, choices=[('pla', 'PLA'), ('petg', 'PETG'), ('abs', 'ABS'), ('nylon', 'Нейлон'), ('other', 'Другое')], default='pla', max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='gunmodule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
