# Generated by Django 5.2.5 on 2026-07-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_airsoftequipment_category_airsoftequipment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('callsign', models.CharField(blank=True, help_text='Необязательное поле', max_length=100, verbose_name='Позывной')),
                ('participation_status', models.CharField(choices=[('yes', 'Да, приеду'), ('no', 'Нет, не приеду'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Статус участия')),
                ('has_car', models.BooleanField(default=False, verbose_name='Есть автомобиль')),
                ('has_equipment', models.CharField(choices=[('yes', 'Есть своя'), ('no', 'Нет, нужна аренда')], default='no', max_length=10, verbose_name='Наличие амуниции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='main.airsoftgame', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Регистрация на игру',
                'verbose_name_plural': 'Регистрации на игры',
                'ordering': ['-registered_at'],
                'unique_together': {('game', 'phone_number')},
            },
        ),
    ]
