# Generated by Django 5.2.5 on 2026-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('player', 'Игрок'), ('commander', 'Командир'), ('admin', 'Администратор')], default='player', max_length=20, verbose_name='Роль'),
        ),
    ]
