# Generated by Django 5.2.5 on 2026-07-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_gameregistration_unique_together_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoftgame',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='airsoftgame',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Предстоит'), ('ongoing', 'Идёт'), ('finished', 'Завершена'), ('archived', 'Архивирована')], default='upcoming', max_length=20, verbose_name='Статус'),
        ),
    ]
