# Generated by Django 5.2.5 on 2026-03-27 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirsoftEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страйбольное оборудование',
                'verbose_name_plural': 'Страйбольное оборудование',
            },
        ),
        migrations.CreateModel(
            name='AirsoftGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Страйкбольная игра', max_length=150, unique=True, verbose_name='Страйкбольные игры')),
                ('date', models.DateField(verbose_name='Дата игры')),
            ],
            options={
                'verbose_name': 'Страйкбольная игра',
                'verbose_name_plural': 'Страйкбольные игры',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Страйбольное оружие', max_length=150, unique=True, verbose_name='Страйбольное оружие')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Страйбольное привод',
                'verbose_name_plural': 'Страйбольные привода',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GunAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='Тип аксессуара')),
            ],
            options={
                'verbose_name': 'Аксессуар для привода',
                'verbose_name_plural': 'Аксессуары для приводов',
            },
        ),
        migrations.CreateModel(
            name='GunModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_url', models.URLField(blank=True, verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': '3D модуль',
                'verbose_name_plural': '3D модули',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тег', max_length=150, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('airsoft_equipment', models.ManyToManyField(blank=True, to='main.airsoftequipment', verbose_name='Страйбольное оборудование')),
                ('airsoft_games', models.ManyToManyField(blank=True, to='main.airsoftgame', verbose_name='Страйбольные игры')),
                ('guns', models.ManyToManyField(blank=True, to='main.gun', verbose_name='Страйбольные привода')),
                ('guns_accessories', models.ManyToManyField(blank=True, to='main.gunaccessory', verbose_name='Страйбольные аксессуары')),
                ('guns_modules', models.ManyToManyField(blank=True, to='main.gunmodule', verbose_name='Страйбольные модули')),
                ('tags', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('airsoft_gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gun', verbose_name='Страйбольное оружие')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'constraints': [models.UniqueConstraint(fields=('id', 'user', 'airsoft_gun'), name='unique_favorite')],
            },
        ),
    ]
